### ISSUE TITLE
Output order of EntityDescriptor elements not kept

### ISSUE THREAD

**Issue by andmor-** [IdentityPython/pyFF#112]
We are experiencing a difference in behavior between our previous pyFF version (late 2014) and any new build from the master branch.
The old version keeps the order of the EntityDescriptor elements on its output across multiple runs, provided that the input does not change. This does not happen in newer builds where the order of EntityDescriptor elements seems rather random at every run.
This creates a problem for us since some of the identity federations we work with, use automated diff based tools to detect updates in our metadata feeds.
I believe I have narrowed it down to pyFF or the Python environment itself. But since I am not so literate in Python it is difficult for me to pinpoint the problem.
I wonder if somebody already ran into a similar issue and if so what could be the solution?

Here is our job.fd:

```
- load:
   - output/md_about_spf_sps.xml
- select: "!//md:EntityDescriptor[md:SPSSODescriptor]"
- xslt:
    stylesheet: tidy.xsl
- finalize:
    name: "http://www.clarin.eu/spf"
    cacheDuration: PT5H
    validUntil: P10D
- publish: output/md_about_spf_sps.xml
- stats
- certreport
```
Any help would be greatly appreciated!
