### ISSUE TITLE
XPath selection does not work anymore when file is specified in the `select` pipe itself

### ISSUE THREAD

**Issue by andmor-** [IdentityPython/pyFF#129]
I use to be able to run the following job:
```
- load fail_on_error True:
    - about_identity_federations_md.xrd
- select: 
    - "output/id_feds/aconet.xml!//md:EntityDescriptor[md:IDPSSODescriptor and not(@entityID='https://blacklisted.IdP')]"
- xslt:
    stylesheet: tidy.xsl
- finalize:
    name: "http://www.clarin.eu/spf"
    cacheDuration: PT5H
    validUntil: P10D
- publish: output/prod_md_about_spf_idps.xml
- stats
- certreport
```
This now exits with:
```
PipeException: empty select - stop
ERROR:root:empty select - stop
```

In order to get it to work, I now need to do it differently:
```
- load fail_on_error True:
    - about_identity_federations_md.xrd
    - output/id_feds/aconet.xml as aconet
- select: 
    - "aconet!//md:EntityDescriptor[md:IDPSSODescriptor and not(@entityID='https://blacklisted.IdP')]"
- xslt:
    stylesheet: tidy.xsl
- finalize:
    name: "http://www.clarin.eu/spf"
    cacheDuration: PT5H
    validUntil: P10D
- publish: output/prod_md_about_spf_idps.xml
- stats
- certreport
```

Is this due to an intentional decision or an unknown issue?

I am using the latest master to date: 7ddc5da6936b8d6724f0ba54b9bec9e5bfc39b05
