### ISSUE TITLE
Support for external parameters

### ISSUE THREAD

**Issue by guillomovitch** [IdentityPython/pyFF#185]
We currently use the same processing pipelines for multiple federation (loading / filtering / signing / publishing), the only difference being the input and output file names. As pyff doesn't seem to support any kind of external input (at least, I couldn't find any hint in documentation or provided examples), we currently generate pipelines on the fly using a templating system.

A simpler way would be to provide a way to override pipeline content, for instance as command line parameter, or environment variable. For instance, the pipeline provided as example 2 could be made generic this way:

```
- load: $url
- select:
   - "!//md:EntityDescriptor[md:IDPSSODescriptor]"
- xslt:
    stylesheet: tidy.xsl
- finalize:
    cacheDuration: PT5H
    validUntil: P10D
- sign:
    key: sign.key
    cert: sign.crt
- publish: $file
```

As used as:
`pyff pipeline.yml -Durl=http://mds.edugain.org -Dfile=/tmp/edugain-idp.xml`
