### ISSUE TITLE
Filtering out entites

### ISSUE THREAD

**Issue by geoffroya** [IdentityPython/pyFF#199]
We would like to filter out entities, based on their entityID from a given stream.
Sample pipeline:

```yaml
---
- load: ./cnous-crous-metadata.xml
- select:
  - "!//md:EntityDescriptor[not(@entityID = 'https://ppidp.messervices.etudiant.gouv.fr/idp/shibboleth')]"
  - "!//md:EntityDescriptor[not(@entityID = 'https://pp.messervices.etudiant.gouv.fr')]"
- stats
```

## Code Version
Pyff 1.1.1

## Expected Behavior
Declared entities

## Current Behavior
When only one statement in `select`, the entity is filtered out:

```
---
total size:     218
selected:       217
          idps: 38
           sps: 179
---
```

When 2 ore more are present, I get much more entities:

```
---
total size:     218
selected:       434
          idps: 77
           sps: 357
---
```

Any clue bout this?

Best regards
Geoff.

**Comment by geoffroya** [comment]
I post the solution, in case someone encouters the "issue" too:

```yaml
---
- load: ./cnous-crous-metadata.xml
- select
- filter:
  - "!//md:EntityDescriptor[not(@entityID = 'https://pp.messervices.etudiant.gouv.fr') and not(@entityID = 'https://ppidp.messervices.etudiant.gouv.fr/idp/shibboleth')]"
- publish: ./filtered.xml
- stats
```

It works. It's quite a long syntax, where I hoped to find a quick primitive, to filter out based on a list of entityIDs.

**Comment by leifj** [comment]
you can just list the entityIDs - I have several instances in production that uses this very setup

**Comment by geoffroya** [comment]
Thank you for your feedback @leifj but I didn't manage to make it work.
Could you please send me a sample, because something like doesn't filter out (ie exlcudes), but only selects the listed entities

```yaml
---
- load: ./cnous-crous-metadata.xml
- select
- filter:
  - https://ppidp.messervices.etudiant.gouv.fr/idp/shibboleth
  - https://pp.messervices.etudiant.gouv.fr
- stats
```

```
$ pyff black-list.yml
---
total size:     218
selected:       2
          idps: 1
           sps: 1
---
```
