### ISSUE TITLE
No parser for metadata signing certificates

### ISSUE THREAD

**Issue by baszoetekouw** [IdentityPython/pyFF#200]
## Code Version
master

## Current Behavior
The [documentation](https://pyff.readthedocs.io/en/latest/usage/examples.html#example-2-grab-the-idps-from-edugain) contains the following example pipeline:
```
- load:
   - http://mds.edugain.org
   - edugain-signer.crt
- select:
   - "http://mds.edugain.org!//md:EntityDescriptor[md:IDPSSODescriptor]"
- xslt:
    stylesheet: tidy.xsl
- finalize:
    cacheDuration: PT5H
    validUntil: P10D
- sign:
    key: sign.key
    cert: sign.crt
- publish: /tmp/edugain-idp.xml
- stats
```
Running this pipeline however, results in the following error message:
```
ERROR:root:No matching parser found for file:///opt/pyff/pyff-env/certs/edugain-singercrt
```

That's unsurprising, because there is no trace of crt or pem parsers in https://github.com/IdentityPython/pyFF/blob/master/src/pyff/parse.py

So the question is: is this an issue with the documentation or with the code?  I can easily work around it by creating a xrd file, but it seems rather overkill the have to wrap two variables in 8 XML tags.  The simple solution, as hinted in the documentation, would be much preferable, afaic.
