### ISSUE TITLE
Metadata of deleted XRD links are still published

### ISSUE THREAD

**Issue by ctriant** [IdentityPython/pyFF#227]
I'm using a pipeline where the metadata URLs are retrieved from a XRD file. When I delete a XRD entry the published xml still includes the entries that correspond to that deleted XRD entry.

The following arguments are used to run pyffd:

```bash
../venv/bin/pyffd --frequency=30 --store_clear --icon_store_clear --loglevel="DEBUG" -H 0.0.0.0 -P 8080 -p /var/run/pyffd.pid -C examples/mdx.fd
```

## Code Version

pyFF master branch 052c556

## Pipeline used
```yaml
- when update:
    - load xrd big.xrd:
        - examples/big.xrd
    - select
    - publish:
        output: "published/test.xml"
        update_store: true
    - break
- when request:
    - select
    - pipe:
        - when accept application/samlmetadata+xml application/xml:
             - emit application/samlmetadata+xml
             - break
        - when accept application/json:
             - discojson
             - emit application/json
             - break`
```
