### ISSUE TITLE
Filtering doesn't work as expected

### ISSUE THREAD

**Issue by cfra** [IdentityPython/pyFF#229]
## Code Version

1.1.5

## Expected Behavior

I have a filter configured in my update pipeline.

I expect pyFF to apply the filter during the loading process, so only entities matching that filter should be listed when browsing metadata or querying via MDQ.

## Current Behavior

All entities loaded from the source are shown.

## Possible Solution

I have a really hard time grasping how the pipelines work. Some more documentation and examples would be really great.

## Steps to Reproduce

Use this pipeline:

```yaml
- when update:
    - load:
        - "http://www.aai.dfn.de/fileadmin/metadata/dfn-aai-test-metadata.xml verify dfn-aai.pem"
    - select
    - filter: 
      - "https://testidp2.aai.dfn.de/idp/shibboleth"
    - break
- when request:
    - select
    - pipe:
        - when accept application/xml:
             - xslt:
                 stylesheet: tidy.xsl
             - first
             - finalize:
                cacheDuration: PT10D
                validUntil: PT5H
             - sign:
                 key: default.key
                 cert: default.crt
             - emit application/xml
             - break
        - when accept application/json:
             - xslt:
                 stylesheet: discojson.xsl
             - emit application/json
             - break
```

Browse pyFF's webinterface.
