### ISSUE TITLE
How do I add support for SHA1 in WSGI scenario

### ISSUE THREAD

**Issue by craftbyte** [IdentityPython/pyFF#234]
I am running pyFF in a Docker container with the following pipeline:
```yaml
- when update:
    - load:
      - https://ds.aai.arnes.si/metadata/arnesaai-edugain.signed.xml
    - break
- when request:
    - select:
    - pipe:
        - when accept application/samlmetadata+xml application/xml:
             - first
             - finalize:
                 cacheDuration: PT5H
                 validUntil: P10D
             - sign:
                 key: sign.key
                 cert: sign.crt
             - emit application/xml
             - break
        - when accept application/json:
             - discojson
             - emit application/json:
             - break
```

When I point SATOSA to it, it requests entities with the SHA1 method, which returns empty results.

Am I doing something wrong or is this a bug?
