### ISSUE TITLE
sign pipe seems to treat arguments as list instead of dict, which causes an error

### ISSUE THREAD

**Issue by Razorfang** [IdentityPython/pyFF#295]
I am currently experimenting with pyFF, and I am trying to use the sign pipe as part of a pipeline

```
  - sign:
    - key: "credentials/test_key.key"
    - cert: "credentials/test_cert.crt"
```

However, this generates the following error:

> Got exception when loading/executing pipe: Missing key and cert arguments to sign pipe

This is despite the fact that I have clearly defined a key and cert in the pipe.

I had a look and I think it's because of this line in builtins.py:

```
if not isinstance(req.args, dict):
    raise PipeException("Missing key and cert arguments to sign pipe")
```

req.args is a list, not a dict, so this check will always fail.

Is my syntax wrong? I also tried using the exact syntax in https://pyff.readthedocs.io/en/latest/usage/examples.html#example-2-grab-the-idps-from-edugain , which is the same as mine but with no dashes preceding the key and cert arguments, but that gives this error instead:

> Got exception when loading/executing pipe: 'NoneType' object is not subscriptable

**Comment by Razorfang** [comment]
I also suspect the same issue could be true for the `finalize` pipeline.

```
- finalize:
  cacheDuration: PT12H
  validUntil: P10D
```

Results in:
```
Got exception when loading/executing pipe: Non-dict args to "finalize" not allowed
```

I am wondering if this is a generic pipeline issue or if this is an issue for specific pipelines.

**Comment by mikaelfrykholm** [comment]
What version are you using?

**Comment by Razorfang** [comment]
I am running from the master branch, not from a specific version. But when I tested this, it was only a few commits after version 2.1.3.

I just did a pull to get the latest changes, and re-tested, and it seems like the issue is still there.

As a refresher:

```
- sign:
  key: "credentials/test_key.key"
  cert: "credentials/test_cert.crt"
```

(or any mixture of dashes and lack of dashes in the arguments) produces

```
ERROR:pyff.api:Exception from processing pipeline: Missing key and cert arguments to sign pipe
```


and

```
- finalize:
  cacheDuration: PT12H
  validUntil: P10D
```

produces

```
ERROR:pyff.api:Exception from processing pipeline: Non-dict args to "finalize" not allowed
```

**Comment by mikaelfrykholm** [comment]
That is how we use it in production. 
```
- when clean:
    - xslt:
       stylesheet: tidy.xsl
    - check_xml_namespaces
    - break
- when update:
    - load:
        - /opt/metadata/swamid-interfederations-qa as swamid-interfederations-qa-dir cleanup clean
        - /opt/metadata/swamid-qa as swamid-qa-dir cleanup clean
        - /opt/metadata/swamid-internal as swamid-internal-dir cleanup clean
    - select
    - fork:
        - select as ds:
            - swamid-internal-dir
            - swamid-qa-dir
            - swamid-interfederations-qa-dir
    - fork:
        # need a uniq name to avoid format problem
        # pyFF caches accept-type and requse selection :-(
        - select as ds-sp:
            - swamid-internal-dir
            - swamid-qa-dir
            - swamid-interfederations-qa-dir
    - fork:
        # swamid-approved.xml
        - select as swamid-approved:
            - swamid-internal-dir
    - break
- when request:
    - select
        - swamid-internal-dir
        - swamid-qa-dir
        - swamid-interfederations-qa-dir
    - pipe:
        - when accept application/samlmetadata+xml application/xml:
             - xslt:
                 stylesheet: tidy.xsl
             - pubinfo:
                 publisher: https://mds.swamid.se/qa/
             - first
             - finalize:
                 baseURL: https://mds.swamid.se/qa/
                 cacheDuration: PT5H
                 validUntil: P10D
             - sign:
                 key: /etc/credentials/pyff-signing-key.pem
                 cert: certs/swamid-qa.crt
             - emit application/xml
             - break
        - when accept application/json:
             - discojson
             - emit application/json:
             - break
        - when accept application/json-sp:
             - discojson_sp
             - emit application/json:
             - break
```
I don't really see a difference with how you use it. And please try with proper 2.1.3 as I have been doing lots of cleanups lately and might have broken something not caught by the tests.

**Comment by Razorfang** [comment]
Thank you for providing an example. That reminds me, I should have been more clear. Here is my full example that I'm trying to get working:

```
- when test:
  - load:
    - /home/jgetty/pyfftest/test-metadata/entities/
  - select
  - finalize:
    cacheDuration: PT12H
    validUntil: P10D
  - sign:
    key: "credentials/test_key.key"
    cert: "credentials/test_cert.crt"
  - publish:
    - "/home/jgetty/pyfftest/test-signed.xml"
```

I am starting the pipeline with this command:

```
gunicorn  --workers=1 --preload --bind 0.0.0.0:8080 -e PYFF_PIPELINE=test.yml --threads 4 --worker-tmp-dir=/dev/shm pyff.wsgi:app
```

and I am invoking it with this API call:

```
curl -XPOST -s http://localhost:8080/api/call/test
```

I have also made sure I'm running version 2.1.3 of pyFF now.

Unfortunately, I still get this error:

```
ERROR:pyff.api:Exception from processing pipeline: Non-dict args to "finalize" not allowed
```

So I'm quite sure that this is an issue in version 2.1.3

**Comment by mikaelfrykholm** [comment]
Ah, I see the problem now I think. 
```
- when test:
  - load:
    - /home/jgetty/pyfftest/test-metadata/entities/
  - select
  - finalize:
      cacheDuration: PT12H
      validUntil: P10D
  - sign:
      key: "credentials/test_key.key"
      cert: "credentials/test_cert.crt"
  - publish:
    - "/home/jgetty/pyfftest/test-signed.xml"
```
Try it with this pipeline instead. Note the indented arguments to sign and finalize
